apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  namespace: group12
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs:
      - job_name: 'Dierentuin'
        static_configs:
          - targets: ['12.web.dops.tech']