name: Create, test, and Publish Dotnet Release

on: 
  push: 
    branches: ["main"] 
  pull_request: 
    branches: ["main"]

jobs: 
  build: 
    runs-on: [ubuntu-latest] 
    steps: 
      - name: Checkout 
        uses: actions/checkout@v4 
      - name: Build and cache Docker image 
        run: |
          docker build --no-cache \
          -t :${{ ljmagalaes/dierentuingroup12:latest }} \
          --target build --build-arg "INCLUDE_UNITTESTING=true" \
          -f ./Dockerfile

  unittesting: 
    runs-on: [ubuntu-latest] 
    needs: build 
    steps: 
      - name: Run dotnet tests inside Docker container 
        run: docker run --entrypoint "" :${{ ljmagalaes/dierentuingroup12:latest }} dotnet test 

  prepare-release: 
    runs-on: [ubuntu-latest] 
    needs: unittesting 
    steps: 
      - name: Docker build as final 
        run: |
          docker build \
          -t :${{ ljmagalaes/dierentuingroup12:latest }}
           -f ./Dockerfile