name: Create, test, and Publish Dotnet Release

on: 
  push: 
    branches: ["test"] 
  pull_request: 
    branches: ["test"]

jobs: 
  build: 
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - name: Install dependencies
        run: dotnet restore
      # - name: Build
      #   run: dotnet build
      - name: Test with the dotnet CLI
        run: dotnet test
        path: ./DierentuinGroup12.Tests






  #   steps: 
  #     - name: Checkout 
  #       uses: actions/checkout@v4 
  #     - name: Build and cache Docker image 
  #       run: |
  #         docker build --no-cache \
  #         -t :${{ ljmagalaes/dierentuingroup12:latest }} \
  #         --target build --build-arg "INCLUDE_UNITTESTING=true" \
  #         -f ./Dockerfile

  # unittesting: 
  #   runs-on: [ubuntu-latest] 
  #   needs: build 
  #   steps: 
  #     - name: Run dotnet tests inside Docker container 
  #       run: docker run --entrypoint "" :${{ ljmagalaes/dierentuingroup12:latest }} dotnet test 

  # prepare-release: 
  #   runs-on: [ubuntu-latest] 
  #   needs: unittesting 
  #   steps: 
  #     - name: Docker build as final 
  #       run: |
  #         docker build \
  #         -t :${{ ljmagalaes/dierentuingroup12:latest }}
  #          -f ./Dockerfile