# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  dierentuin:
    image: dierentuin
    build:
      context: .
      dockerfile: Dierentuin/Dierentuin/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5075:5075
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:c:\remote_debugger:rw
