apiVersion: v1
kind: Pod
metadata:
  annotations:
    branch: refs/heads/main
    cni.projectcalico.org/containerID: 4b1cbd195ff242be972062d878e84055bdcbb4568c1a34bd56062e3e3dd84a05
    cni.projectcalico.org/podIP: 10.1.139.17/32
    cni.projectcalico.org/podIPs: 10.1.139.17/32
    commit: 7e4f36fe8830da836eaa1b0735b594fc028d42c4
    createdBy: rikb03
    deployTimestamp: "1719005868877"
    jobName: deploy
    provider: GitHub
    repository: rikb03/WH-SL2B
    run: "9620092328"
    runUri: https://github.com/rikb03/WH-SL2B/actions/runs/9620092328
    workflow: CI - .NET
  creationTimestamp: "2024-06-21T21:37:50Z"
  generateName: group12-5747996f9-
  labels:
    app: group12
    pod-template-hash: 5747996f9
  name: group12-5747996f9-x94bj
  namespace: group12
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: group12-5747996f9
    uid: 127c9947-c3bb-41a2-ab5c-cd9bd6d39956
  resourceVersion: "5236733"
  uid: e5bf3deb-b330-4c1f-9a04-391f30fa50c0
spec:
  containers:
  - image: ljmagalaes/dierentuingroup12:latest
    imagePullPolicy: Always
    name: group12
    ports:
    - containerPort: 8080
      name: web
      protocol: TCP
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 250m
        memory: 64Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-75rjp
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: regcred
  nodeName: pi7
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-75rjp
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-06-21T21:38:29Z"
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2024-06-21T21:37:50Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-06-21T21:38:48Z"
    message: 'containers with unready status: [group12]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-06-21T21:38:48Z"
    message: 'containers with unready status: [group12]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-06-21T21:37:50Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://c120e79b1a5e5eec41be643427aba284155b328c7bf1d267b1c547509230b7b9
    image: docker.io/ljmagalaes/dierentuingroup12:latest
    imageID: docker.io/ljmagalaes/dierentuingroup12@sha256:ede544a890eea22479c8761ca2ed1996af6690bbe1aadafa3bf368c41b3ad291
    lastState:
      terminated:
        containerID: containerd://c120e79b1a5e5eec41be643427aba284155b328c7bf1d267b1c547509230b7b9
        exitCode: 1
        finishedAt: "2024-06-21T21:42:03Z"
        reason: Error
        startedAt: "2024-06-21T21:42:03Z"
    name: group12
    ready: false
    restartCount: 5
    started: false
    state:
      waiting:
        message: back-off 2m40s restarting failed container=group12 pod=group12-5747996f9-x94bj_group12(e5bf3deb-b330-4c1f-9a04-391f30fa50c0)
        reason: CrashLoopBackOff
  hostIP: 10.8.231.17
  hostIPs:
  - ip: 10.8.231.17
  phase: Running
  podIP: 10.1.139.17
  podIPs:
  - ip: 10.1.139.17
  qosClass: Burstable
  startTime: "2024-06-21T21:37:50Z"
