// <auto-generated />
using System;
using Dierentuin.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dierentuin.Migrations
{
    [DbContext(typeof(DierentuinContext))]
    [Migration("20240626124816_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("Dierentuin.Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActivityPattern")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("categories_id");

                    b.Property<int>("Dietary")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EnclosureId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enclosures_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Prey")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SecurityRequirement")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<double>("SpaceRequirement")
                        .HasColumnType("REAL")
                        .HasColumnName("spaceRequirement");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("EnclosureId");

                    b.ToTable("animals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActivityPattern = 0,
                            CategoryId = 6,
                            Dietary = 4,
                            EnclosureId = 1,
                            Name = "Tremayne",
                            Prey = 6,
                            SecurityRequirement = 1,
                            Size = 3,
                            SpaceRequirement = 76.005636193022866,
                            Species = "Aquatic Animals"
                        },
                        new
                        {
                            Id = 2,
                            ActivityPattern = 2,
                            CategoryId = 5,
                            Dietary = 3,
                            EnclosureId = 5,
                            Name = "Jeffry",
                            Prey = 3,
                            SecurityRequirement = 0,
                            Size = 3,
                            SpaceRequirement = 43.983474680949378,
                            Species = "Ungulates"
                        },
                        new
                        {
                            Id = 3,
                            ActivityPattern = 0,
                            CategoryId = 8,
                            Dietary = 1,
                            EnclosureId = 5,
                            Name = "Miller",
                            Prey = 2,
                            SecurityRequirement = 2,
                            Size = 1,
                            SpaceRequirement = 72.21702100520362,
                            Species = "Insects"
                        },
                        new
                        {
                            Id = 4,
                            ActivityPattern = 1,
                            CategoryId = 9,
                            Dietary = 2,
                            EnclosureId = 8,
                            Name = "Arden",
                            Prey = 6,
                            SecurityRequirement = 1,
                            Size = 1,
                            SpaceRequirement = 18.966558877529501,
                            Species = "Birds"
                        },
                        new
                        {
                            Id = 5,
                            ActivityPattern = 1,
                            CategoryId = 5,
                            Dietary = 1,
                            EnclosureId = 9,
                            Name = "Tavares",
                            Prey = 5,
                            SecurityRequirement = 0,
                            Size = 1,
                            SpaceRequirement = 47.826318734103445,
                            Species = "Bovines"
                        },
                        new
                        {
                            Id = 6,
                            ActivityPattern = 2,
                            CategoryId = 6,
                            Dietary = 1,
                            EnclosureId = 7,
                            Name = "Zula",
                            Prey = 9,
                            SecurityRequirement = 1,
                            Size = 5,
                            SpaceRequirement = 17.620696395763002,
                            Species = "Pachyderms"
                        },
                        new
                        {
                            Id = 7,
                            ActivityPattern = 2,
                            CategoryId = 2,
                            Dietary = 4,
                            EnclosureId = 1,
                            Name = "Juliet",
                            Prey = 8,
                            SecurityRequirement = 0,
                            Size = 3,
                            SpaceRequirement = 66.017261503547758,
                            Species = "Arachnids"
                        },
                        new
                        {
                            Id = 8,
                            ActivityPattern = 2,
                            CategoryId = 3,
                            Dietary = 2,
                            EnclosureId = 3,
                            Name = "Jevon",
                            Prey = 2,
                            SecurityRequirement = 0,
                            Size = 5,
                            SpaceRequirement = 5.710742433160922,
                            Species = "Pachyderms"
                        },
                        new
                        {
                            Id = 9,
                            ActivityPattern = 2,
                            CategoryId = 1,
                            Dietary = 2,
                            EnclosureId = 3,
                            Name = "Jaquan",
                            Prey = 3,
                            SecurityRequirement = 1,
                            Size = 1,
                            SpaceRequirement = 95.890223980597995,
                            Species = "Arachnids"
                        },
                        new
                        {
                            Id = 10,
                            ActivityPattern = 1,
                            CategoryId = 4,
                            Dietary = 3,
                            EnclosureId = 6,
                            Name = "Jermey",
                            Prey = 1,
                            SecurityRequirement = 1,
                            Size = 1,
                            SpaceRequirement = 69.563248388446652,
                            Species = "Canines"
                        });
                });

            modelBuilder.Entity("Dierentuin.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Odit eum exercitationem.",
                            Name = "Aquatic Animals"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Itaque labore esse.",
                            Name = "Aquatic Animals"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Facilis quaerat repellat.",
                            Name = "Bats"
                        },
                        new
                        {
                            Id = 4,
                            Description = "In dolor reprehenderit.",
                            Name = "Ungulates"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Et nihil beatae.",
                            Name = "Insects"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Voluptatem dolorum tempora.",
                            Name = "Mustelids"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Quaerat eius consectetur.",
                            Name = "Reptiles"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Nam facere hic.",
                            Name = "Bats"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Enim harum ullam.",
                            Name = "Rodents"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Deleniti delectus beatae.",
                            Name = "Mammals"
                        });
                });

            modelBuilder.Entity("Dierentuin.Models.Enclosure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Climate")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Habitat")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("SecurityLevel")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Size")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("enclosures");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Climate = 2,
                            Habitat = 1,
                            Name = "Territory",
                            SecurityLevel = 1,
                            Size = 14.771890186205578
                        },
                        new
                        {
                            Id = 2,
                            Climate = 1,
                            Habitat = 3,
                            Name = "Pool",
                            SecurityLevel = 2,
                            Size = 45.078704872757662
                        },
                        new
                        {
                            Id = 3,
                            Climate = 0,
                            Habitat = 2,
                            Name = "Aviary",
                            SecurityLevel = 0,
                            Size = 25.972496293230325
                        },
                        new
                        {
                            Id = 4,
                            Climate = 2,
                            Habitat = 3,
                            Name = "Habitat",
                            SecurityLevel = 0,
                            Size = 48.447796497417322
                        },
                        new
                        {
                            Id = 5,
                            Climate = 0,
                            Habitat = 2,
                            Name = "Paddock",
                            SecurityLevel = 0,
                            Size = 23.876876249455776
                        },
                        new
                        {
                            Id = 6,
                            Climate = 2,
                            Habitat = 2,
                            Name = "Territory",
                            SecurityLevel = 1,
                            Size = 46.042498711809728
                        },
                        new
                        {
                            Id = 7,
                            Climate = 1,
                            Habitat = 0,
                            Name = "Grove",
                            SecurityLevel = 0,
                            Size = 30.081723610151997
                        },
                        new
                        {
                            Id = 8,
                            Climate = 0,
                            Habitat = 1,
                            Name = "House",
                            SecurityLevel = 2,
                            Size = 52.208789955654453
                        },
                        new
                        {
                            Id = 9,
                            Climate = 1,
                            Habitat = 0,
                            Name = "Cave",
                            SecurityLevel = 1,
                            Size = 83.003769239213298
                        },
                        new
                        {
                            Id = 10,
                            Climate = 0,
                            Habitat = 2,
                            Name = "Cave",
                            SecurityLevel = 0,
                            Size = 2.1855974660035917
                        });
                });

            modelBuilder.Entity("Dierentuin.Models.Animal", b =>
                {
                    b.HasOne("Dierentuin.Models.Category", "Category")
                        .WithMany("Animals")
                        .HasForeignKey("CategoryId");

                    b.HasOne("Dierentuin.Models.Enclosure", "Enclosure")
                        .WithMany("Animals")
                        .HasForeignKey("EnclosureId");

                    b.Navigation("Category");

                    b.Navigation("Enclosure");
                });

            modelBuilder.Entity("Dierentuin.Models.Category", b =>
                {
                    b.Navigation("Animals");
                });

            modelBuilder.Entity("Dierentuin.Models.Enclosure", b =>
                {
                    b.Navigation("Animals");
                });
#pragma warning restore 612, 618
        }
    }
}
